#!/bin/bash

#FILES=$TRAVIS_BUILD_DIR/tests/Selenium/errorShots/*
#echo "--- Displaying content of Selenium error screenshots\n"
#for f in $FILES
#do
#  echo "--- Displaying content of $f ...\n"

#  echo "data:image/png;base64,$(base64 -w 0 $f)"
#done

FILES=$TRAVIS_BUILD_DIR/tests/E2E/screenshots/*
echo "--- Displaying content of E2E error screenshots\n"
for f in $FILES
do
  echo "--- Displaying content of $f ...\n"

  echo "data:image/png;base64,$(base64 -w 0 $f)"
done
