#!/bin/bash

if [[ $EXTRA_TESTS != *"functional"* ]]; then
  exit 0
fi

bash $TRAVIS_BUILD_DIR/travis-scripts/install-prestashop

echo "* Installing functional tests ...";

cd $TRAVIS_BUILD_DIR/tests/E2E && npm install

echo "* Running functional tests ...";
#path=regular/03_create_product.js npm run specific-test
npm test -- --MODULE=ps_legalcompliance
exit $?
