#!/bin/bash

if [[ $EXTRA_TESTS != *"functional"* ]]; then
  exit 0
fi

mysql -u root -e "DROP DATABASE IF EXISTS \`prestashop\`;"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS \`prestashop\`;"

echo "* Installing functional tests ...";

cd $TRAVIS_BUILD_DIR/tests/E2E && npm install

echo "* Running functional tests ...";
npm test -- --MODULE=ps_legalcompliance
exit $?
